### ISSUE TITLE
On PickPhoto, Photo's orientation gets changed from Portrait to Landscape on Android Device

### ISSUE THREAD

**Issue by rishabhsaha** [jamesmontemagno/MediaPlugin#268]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: Samsung Galaxy Tab A (Android Version 5.1.1)
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 2.3.4.247 (Xamarin Forms)
Versions of other things you are using:

### Steps to reproduce the Behavior
1) Pick a portrait photo from the album
2) The orientation gets changed to landscape
### Expected Behavior
1) A portrait photo should show up with portrait orientation in the Image View control

### Actual Behavior
1) The photo appears as landscape

### Code snippet
if (String.Equals(action, "Take Photo"))
                    {
                        await CrossMedia.Current.Initialize();

                        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                        {
                            await DisplayAlert("No Camera", ":( No camera available.", "OK");
                            return;
                        }

                        var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                        {
                            SaveToAlbum = true
                           
                        });

                        if (file == null)
                            return;

                      
                        imageData = GetImageStreamAsBytes(file.GetStream());
                       
                        DefaultPhoto.Source = ImageSource.FromStream(() => new MemoryStream(imageData));

                      
                    }
### Screenshots
![screenshot_2017-06-09-10-16-37](https://user-images.githubusercontent.com/12716801/26979485-ed6970ce-4cfc-11e7-9b88-1001b4edd383.png)

**Comment by jamesmontemagno** [comment]
What library are you using to display your images? It may have exif data in it already and rotating it in the gallery, but not in Xamarin.Forms. FFImageLoading will read the exif data for you.

**Comment by rishabhsaha** [comment]
Hi,
I am using the Xamarin.Forms.Image control to display the images.
//DefaultPhoto is the Xamarin Forms Image Control

image = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(options);
imageData = GetImageStreamAsBytes(image.GetStream());
DefaultPhoto.Source = ImageSource.FromStream(() => new MemoryStream(imageData));

Is there something that might cause the Image viewer to do the rotation on it's own? The image been selected in the gallery is a potrait image, not sure what's causing it to rotate.

**Comment by jamesmontemagno** [comment]
There could be some odd exif data in the photos telling me to rotate it or perhaps the gallery is. There is flag on the options that you pass in called "RotateImage" set it to false and see what happens.

**Comment by AdrianZghibarta** [comment]
@jamesmontemagno did you managed to solve this issue? I have the same problem.

**Comment by AdrianZghibarta** [comment]
I have found a solution .. don't know if it's a good one, but I've noticed that if I set a custom image size and custom compression quality, the image will not be rotated. For my exemple I've used something like :
`file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions 
					{ 
						CustomPhotoSize = 500,
						CompressionQuality = 80
					});`

**Comment by jamesmontemagno** [comment]
I believe this was actually fixed in the beta actually. Going to close for now.

**Comment by hjavaher** [comment]
I'm still having this issue and have used both FFImageLoading and ImageCircle.Forms.Plugin :/

**Comment by Razmehra** [comment]
using file's Path instead of file's AlbumPath for Image source will resolve this issue.

**Comment by mmandt** [comment]
After much work, I solved this problem by loading the image as SkiaSharp image and the resaving it:

` var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions {
				RotateImage = false,
				AllowCropping = true,
				PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small,
				SaveToAlbum = false
			});

			string path;
			if (file != null) {

				path = file.Path;
				Stream stream = new MemoryStream(File.ReadAllBytes(path));
				
				file.Dispose();

				SKManagedStream skStream = new SKManagedStream(stream);
				SKBitmap bitmap = SKBitmap.Decode(skStream);

				var image = SKImage.FromBitmap(bitmap);
				var data = image.Encode(SKEncodedImageFormat.Jpeg, 90);

				var newstream = new FileStream(path, FileMode.OpenOrCreate, FileAccess.Write);
				data.SaveTo(newstream);
}`
