### ISSUE TITLE
Possibile Regression: Native Android (Pixel,etc) stops instantly when trying to capture video 

### ISSUE THREAD

**Issue by fsaffioti** [jamesmontemagno/MediaPlugin#568]
**Bug Information**

Version Number of Plugin: 4.0.0.9
Device Tested On: Google Pixel 2 android 8.1
Simulator Tested On: Android Studio simulators 8.1., 8.0
Version of VS: Visual Studio 7.5.2
Version of Xamarin: 4.4.1.193
Versions of Xamarin.Android SDK: 8.3.3.2

**Expected Behavior**
Start recoding video should be uninterrupted until either stopped by the user or reached the desired size or reached the desired time

**Actual Behavior**
When I tap on the button to start recording the device start recoding for 1 second.  When you play it it looks like a single picture.
Also tried without the DesiredSize property of StoreVideoOptions.
it works as expected with other phones: tested on Samsung S8 and Huawei Honor

**Code snippet**

                if (CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakeVideoSupported)
                {
                    var file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
                    {
                        Name = $"{fileName}", //={name}_{DateTime.Now.ToString("yyyyMMddHHmmss")}.mp4
                        SaveToAlbum = false,
                        Quality = VideoQuality.Low,
                        DesiredLength = TimeSpan.FromSeconds(Constants.MaxVideoLengthSec),

                    });
         }

Also tried

                    var file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
                    {
                        Name = $"{fileName}",
                        SaveToAlbum = false,
                        Quality = VideoQuality.Low,
                        DesiredSize = 45 * 1000000,
                        CompressionQuality = 0,
                    });

**Comment by jamesmontemagno** [comment]
See this thread: https://github.com/jamesmontemagno/MediaPlugin/issues/514

**Comment by jamesmontemagno** [comment]
I manually filter out the pixel here: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin/Android/MediaPickerActivity.cs#L117-L129

This is due to a bug in the pixel itself.

**Comment by nunohorta** [comment]
Hi @jamesmontemagno . I'm still seeing this bug on 4.0.0.9. Should I be on the latest beta instead?

**Comment by fsaffioti** [comment]
latest beta of the plugin(4.0.1.1-beta) solve the issue. Tested on Emulator (not real Pixel device)

**Comment by jamesmontemagno** [comment]
I pushed out 4.0.1.1

**Comment by marikatz** [comment]
Updated to 4.0.1.1 but I'm still seeing this bug on Pixel 2 XL with Android 8.1.
