### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by gnamse** [jamesmontemagno/MediaPlugin#624]
Full stack trace can be found here:
https://gist.github.com/gnamse/fdac7f40cb51ab5cba1b1facec1682aa

## Bug Information
Random crash when i take picture with the camera and save the data. Somtimes it works and other times i get this error.

Version Number of Plugin: **4.0.1.5**
Device Tested On: **Google Pixel**
Simulator Tested On: **Android 8.0 - API 26**
Version of VS: **15.8.6**
Version of Xamarin: **4.11.0.776**
Versions of other things you are using:
 - **System.Reactive 4.0.0**
 - **Prism.DryIoc.Forms 7.0.0.396**

### Code snippet
```
 Observable.FromAsync(() => CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions()
            {
                SaveToAlbum = true,
                Directory = "Demo",
                DefaultCamera = CameraDevice.Rear,
                CompressionQuality = 80,
                CustomPhotoSize = 50,
                Name = $"Demo_{DateTime.UtcNow}.jpg"
            })).Subscribe(async photo =>
            {
                if (photo == null)
                {
                       return;
                }

                SelectedImageSource = ImageSource.FromStream(() =>
                {
                    var stream = photo.GetStream();
                    return stream;
                });
                Path= photo.Path;
            });
```

**Comment by gnamse** [comment]
Looks like this issue has been fixed after updating xamarin froms to **3.3.0.967583**

**Comment by marcojak** [comment]
I still get the same error trying to take a picture.
Plugin Version: 4.0.1.5
Xamarin Forms version: 4.1.0.581479

Before updating to the new Xamarin Forms, the app was working fine.
