### ISSUE TITLE
Dismissing Gallery Select Issues Only one operation

### ISSUE THREAD

**Issue by Trevonious** [jamesmontemagno/MediaPlugin#666]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: Latest prerelease 4.2.0-beta
Device Tested On: Galaxy Tab 3, iPad Gen 6
Simulator Tested On: 
Version of VS: VS Enterprise 2017 (2) - 15.9.4
Version of Xamarin: 4.12.3.77
Versions of other things you are using:

### Steps to reproduce the Behavior

Android:
1. Click button to launch the Gallery Select window
2. Click the onscreen or hardware back button

iOS:
1. Click button to launch the Gallery Select popup
2. Tap outside the popup, to dismiss it
3. Click the button to launch the Gallery Select popup, again

### Expected Behavior

Android:
Tapping the onscreen or hardware back buttons should close the Gallery Select window, without throwing exceptions.

iOS:
Tapping outside the Gallery Select popup should dismiss the popup, similarly to clicking the "Cancel" button. When clicking "Cancel" on the Gallery Select popup, PickPhotosAsync() returns an empty list. This would be the ideal behavior when clicking outside the dialog. Tapping the button again to launch the Gallery Select should launch the popup, as normal.

### Actual Behavior

Android:
A null exception is thrown, from PickPhotosAsync.

iOS:
Get a popup that says "Only one operation can be active at at time." PickPhotosAsync() never returns anything.

### Code snippet

    PickMediaOptions mediaOptions = new PickMediaOptions
    {
        PhotoSize = PhotoSize.Large,
        CompressionQuality = 92
    };

    Photos = new List<ImageSource>();

    try
    {
        files = await CrossMedia.Current.PickPhotosAsync(mediaOptions);
    }
    catch (Exception ex)
    {
        await ParentView.ShowAlert("", ex.Message, "Okay");
    }

    if (files == null || files.Count == 0)
        return;

    foreach (MediaFile image in files)
    {
        imageSource = ImageSource.FromStream(() =>
        {
            var stream = image.GetStream();

            return stream;
        });

        Photos.Add(imageSource);
    }

### Screenshots

![android](https://user-images.githubusercontent.com/5677927/53577722-2a991080-3b44-11e9-9371-1996c3467406.jpg)

![ios](https://user-images.githubusercontent.com/5677927/53577773-47cddf00-3b44-11e9-888e-b79d53ed26b7.PNG)

**Comment by Trevonious** [comment]
#598 #649

**Comment by Trevonious** [comment]
Android part of this bug may have been fixed by #649.

The iOS error looks like it is coming from [this line](https://github.com/vagrawal1986/MediaPlugin/blob/18301e6758cdc3141c6c04feed31513b42b33539/src/Media.Plugin/iOS/MediaImplementation.cs#L349). From my very limited understanding of how this stuff works, it looks like the "pickerDelegate" needs to be nullified when the popup is closed. This is done in the [Dispose](https://github.com/vagrawal1986/MediaPlugin/blob/18301e6758cdc3141c6c04feed31513b42b33539/src/Media.Plugin/iOS/MediaImplementation.cs#L403) method. My guess is that Dispose is not being triggered, when dismissing the popup by clicking outside of it.

**Comment by hussainmorbi** [comment]
has this issue been resolved yet when using PickPhotosAsync on iOS?. I have not seen any updates made on the master branch to rectify this as I am still seeing the issue occur when click outside of the popup? It works just fine when using PickPhotoAsync, just not when using PickPhotosAsync

**Comment by tgriggs-4tell** [comment]
@hussainmorbi It has not been fixed for iOS, as far as I know

**Comment by vibhatt** [comment]
Any update on this? We are experiencing this in our iOS app when the user presses home button in the middle of taking a picture. The next time the TakePhotoAsync(StoreCameraMediaOptions options) is called the picker object is not dismissed before hand and creates "Only one operation can be active at at time." error.
